### ISSUE TITLE
Generate Access Token Doesn't Work

### ISSUE THREAD

**Issue by sim1camporeale** [rcgroot/jenkins-publish-over-dropbox-plugin#2]
I tried your plugin. When I click on Generate Access Token it sends me to dropbox. But dropbox gives me an error and I'm unable to generate required token.
Should I provide you other informations?

Can I help you?

**Comment by rcgroot** [comment]
The client secret for the plugin has been revoked. I'll create a new build next week and add some documentation on how to add your own Dropbox client secret when building from source. 

A fix should be adding valid values to https://github.com/rcgroot/jenkins-publish-over-dropbox-plugin/blob/develop/src/main/java/org/jenkinsci/plugins/publishoverdropbox/domain/Config.java and building from source.

**Comment by rcgroot** [comment]
The RC2 build contains new Dropbox tokens

https://github.com/rcgroot/jenkins-publish-over-dropbox-plugin/releases/tag/1.0-rc2
