### ISSUE TITLE
How to use in pipeline?

### ISSUE THREAD

**Issue by Zomis** [rcgroot/jenkins-publish-over-dropbox-plugin#6]
It is said that the plugin works with Jenkins pipeline, but I can find absolutely no documentation about how. Please add some documentation for this.

Or explain to me and I can give you a pull request with documentation.

**Comment by rcgroot** [comment]
So the documentation is hosted at:
https://wiki.jenkins.io/display/JENKINS/Publish+over+Dropbox+Plugin
which references: 
https://jenkins.io/doc/book/pipeline/

I take a look if I can clarify that from the Github project page.

**Comment by Zomis** [comment]
https://jenkins.io/doc/book/pipeline/ doesn't mention anything about the Dropbox plugin. I know how to use Pipeline in general, but how to tell the pipeline to publish over Dropbox?

Compare with for example [documentation for Kubernetes-pipeline-plugin](https://github.com/jenkinsci/kubernetes-pipeline-plugin/blob/master/kubernetes-steps/readme.md) which tells you exactly which steps to use in the Jenkinsfile for the functionality.

**Comment by rcgroot** [comment]
I see, when writing straight in a Jenkins file you don't get to see the documentation. I suggest to consult the Snippet Generator in Jenkins to help create a dropbox snippet for your Jenkins file.

**Comment by Zomis** [comment]
Thanks. I had forgotten to update the plugin, that's why I didn't saw it there before.

I would recommend documenting it in README.md as well.
